version: '3.9'

services:
  api:
    container_name: api
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${API_PORT}:${API_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes: 
     - ./app:/app
    networks:
      - ergopad-net
    # t3.xlarge uses 4 vcpu, 2 cores; recommendation to do 2*cores+1??
    command: uvicorn main:app --reload --workers 17 --reload-dir /app --host 0.0.0.0 --port ${API_PORT} --proxy-headers --use-colors --forwarded-allow-ips '52.72.64.235'
    # command: uvicorn main:app --workers 4 --host 0.0.0.0 --port ${API_PORT}

networks:
  ergopad-net:
    external: true
  net:
    driver: bridge
