version: '3.9'

services:
  api:
    container_name: api
    env_file: ${ENV_FILE}
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - ${API_PORT}:${API_PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 90s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes: 
     - ./app:/app
    networks:
      - ergopad-data_net
      - ergopad-node_net
    command: uvicorn main:app --workers 4 --host 0.0.0.0 --port ${API_PORT} --proxy-headers --use-colors --forwarded-allow-ips '52.72.64.235'
    # command: uvicorn main:app --reload --workers 4 --reload-dir /app --host 0.0.0.0 --port ${API_PORT} --proxy-headers --use-colors --forwarded-allow-ips '52.72.64.235'
    # command: tail /dev/null -f

    # NOTE: 5/2022 Leif, using gunicorn seems to lock up on certain calls; could not find a configuration that worked; uvicorn does not have same issue
    # uvicorn.workers.UvicornH11Worker # use for pure python implementation
    # command: python -m gunicorn --bind :8000 --workers 4 main:app --worker-class uvicorn.workers.UvicornWorker --preload --timeout 0 --graceful-timeout 0 --worker-tmp-dir /dev/shm --keep-alive 2 

networks:
  ergopad-data_net:
    external: true
  ergopad-node_net:
    external: true
  net:
    driver: bridge
